### ISSUE TITLE
Feature request: UDP API for driver

### ISSUE THREAD

**Issue by r57zone** [HelenXR/openvr_survivor#2]
del

**Comment by HelenXR** [comment]
Thank you for your detailed description. i think your suggest is good.
but I'm on a business trip this week,after this week I'll look into your content in detail.

**Comment by virbiling** [comment]
@r57zone 
Provides access to position and rotation via socket.
But now the situation is VR display data is not out of line, the majority of equipment to obtain the position and rotation of the general information or by way of USB, of course one day this 60GHZ technology is mature enough, will wireless way to make VR better.

**Comment by HelenXR** [comment]
@r57zone 
But now the situation is VR display data is not out of line, the majority of equipment to obtain the position and rotation of the general information or by way of USB, of course one day this 60GHZ technology is mature enough, will wireless way to make VR better.

**Comment by r57zone** [comment]
@HelenXR UDP is needed for DIY VR headset and DIY VR controllers. With UDP the driver will be universal for DIY.

For example, there are projects Arduino Vive Controller or HDMI-display + tracker Arduino, Android VR or etc.

**Comment by HelenXR** [comment]
@r57zone 
It looks good, and I hope you can put this part in submission.
This week I will submit 2 six DOF modules（ximmerse&nolo）
