### ISSUE TITLE
请问下大佬，右控制器的按钮好像按了没反应?

### ISSUE THREAD

**Issue by as8190255** [HelenXR/openvr_survivor#3]
不好意思萌新打扰一下，我试着照着以下按钮操作右手控制器，不知道为什么好像没反应？
right controller button information:
	Menu button:'VK_BACK'
	Trackedpad Left:'VK_KEY_F'
	Trackedpad Up:'VK_KEY_T'
	Trackedpad Right:'VK_KEY_H'
	Trackedpad Down:'VK_KEY_G' or 'VK_KEY_B'
	System Button:'VK_ESCAPE'
	Trigger:'VK_SPACE','7','9'
	Grip Button:'VK_KEY_9'
	Trackpad Press:'VK_KEY_0'

请问这种事情一般是什么情况，其他涉及到角度位置的操作按钮都是可以的。
如有知道原因的万分感谢告知。

**Comment by HelenXR** [comment]
@as8190255 抱歉,按钮部分确实有问题,最初调试时有验证过此功能,是正常的,我不确定是哪个提交导致的问题,你可以尝试回退到之前版本试试,或则等到月底我抽一些时间来修复.

**Comment by as8190255** [comment]
@HelenXR  十分感谢回答，但是我在commits中找了老版本的下载过来，然后使用CMake 3.11.0-rc1 在生成项目的时候报错了。以下是错误内容:

CMake Error at CMakeLists.txt:30 (add_library):
  Cannot find source file:
    include
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at CMakeLists.txt:30 (add_library):
  No SOURCES given to target: driver_openvr_survivor

最新版的不会出这个问题，看不懂缺少了什么东西
第一次使用CMake，刚接触C++没多久现在有点懵比。

**Comment by HelenXR** [comment]
@as8190255 抱歉,之前有事耽误了,按键问题已修复,提交号:a172f0

**Comment by as8190255** [comment]
喔~~~ 已经可以了，谢谢。
